// ─── Decision Analysis Component ──────────────────────────────────────────────
//
// Option comparator: lets clinical teams define 2–4 strategic options and see
// the expected value tradeoffs side-by-side.
//
// Key metrics displayed:
//   eROI             = eNPV / Dev Cost
//   Marginal eROI    = ΔeNPV / |ΔDev Cost| vs Option A
//   eNPV             = PTRS × Revenue PV − Dev Cost PV
//   Risk range       = eNPV at PTRS CI bounds
//
// ─────────────────────────────────────────────────────────────────────────────

import React, { useState, useMemo, useEffect, useRef } from "react";
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip,
  ResponsiveContainer, Cell, ScatterChart, Scatter, ZAxis,
} from "recharts";
import type { Valuation } from "../lib/types";
import DevPathSpine from "./DevPathSpine";
import {
  buildBaseContext,
  computeAllOptions,
  computeOption,
  generateBimodalVoiOption,
  type OptionInputs,
  type OptionResult,
  type BaseContext,
} from "../lib/decision-analysis";
import type { EffectPrior } from "../lib/effect-prior";
import type { DevPlanResult } from "../lib/dev-plan";
import { selfCheck, viewFromOption, flagsFromOption } from "../lib/self-check";

// ─── Prop types ────────────────────────────────────────────────────────────────

// The generated advisor state worth surviving a reload (the transient input/loading/error flags are NOT
// persisted). Lifted so the parent can put it in the last-active snapshot — otherwise the whole Strategy
// Advisor (options, summary, insight, chat) re-blanks on every reload while everything else restores.
export type DecisionPersistState = {
  open: boolean;
  options: OptionInputs[];
  aiSummary: string | null;
  aiInsight: string | null;
  chatHistory: { role: "user" | "assistant"; content: string }[];
};

type Props = {
  valuation: Valuation;
  out: { ptrs: number; revenuePV: number; devCostPV: number; rnpv: number };
  ptrsResult: any;   // from /api/ptrs-score
  layer2Result: any; // from /api/ptrs-layer2
  effectPrior?: EffectPrior | null; // from /api/effect-prior, if loaded
  devPlan?: DevPlanResult | null;   // from computeDevPlan, if available
  persisted?: DecisionPersistState | null;               // restored generated state (auto-restore on reload)
  onPersistedChange?: (s: DecisionPersistState) => void;  // report generated state up so it can be persisted
};

// ─── Colour palette ────────────────────────────────────────────────────────────
// Option A is always accent green; options B/C/D get distinct colours.
// The 5th slot (purple/star) is reserved for the auto-generated
// Early-Signal Resolver option — never user-assignable.

const OPTION_COLORS = ["#10b981", "#3b82f6", "#f59e0b", "#ec4899", "#a855f7"];
const OPTION_LABELS = ["A", "B", "C", "D", "★"];

// ─── Format helpers (self-contained — not imported from index.tsx) ─────────────

function fmtM(n?: number | null): string {
  if (n == null || Number.isNaN(n)) return "—";
  const abs = Math.abs(n);
  if (abs >= 1000) return `$${(n / 1000).toFixed(1)}B`;
  if (abs >= 1)    return `$${n.toFixed(0)}M`;
  return `~$0`;
}
// Whole % by default (render boundary only; internal values untouched).
function fmtPct(n?: number | null, dp = 0): string {
  if (n == null || Number.isNaN(n)) return "—";
  return `${(n * 100).toFixed(dp)}%`;
}
function fmtX(n: number | null): string {
  if (n == null) return "—";
  return `${n >= 0 ? "" : ""}${n.toFixed(2)}x`;
}



// ─── Result Card ───────────────────────────────────────────────────────────────
// Side-by-side card showing computed results for one option.

function ResultCard({
  result, index, isBaseline, isAutoGenerated, isRecommended, onApplyDesign,
}: {
  result: OptionResult;
  index: number;
  isBaseline: boolean;
  isAutoGenerated?: boolean;
  isRecommended?: boolean;  // engine-computed (highest eNPV), NOT the LLM's prose pick
  // Layer 2: send free-form design text to the interpreter; it sets the validated spec on the option
  // and triggers the existing recompute. The card NEVER builds a spec or computes a number.
  onApplyDesign?: (optionId: string, text: string) => Promise<{ ok: boolean; error?: string }>;
}) {
  const color = OPTION_COLORS[index] ?? "#6b7280";
  const label = OPTION_LABELS[index] ?? String(index + 1);
  const { eROI, marginalEROI, eNPVM, eNPVLowM, eNPVHighM, ptrs, ptrsCI, peakSalesM, devCostM, deltaENPVM, deltaCostM, keyDrivers, voiENPVM, durationMonths } = result;

  // Layer 2 "describe a design" widget — LOCAL UI state only (raw text + call status). No spec, no number.
  const [designText, setDesignText] = useState("");
  const [designPending, setDesignPending] = useState(false);
  const [designError, setDesignError] = useState<string | null>(null);

  // Read-only self-check for this option (observes & flags; never adjusts a value).
  const selfReport = selfCheck({ view: viewFromOption(result), flags: flagsFromOption(result) });
  const selfBlockers = selfReport.checks.filter((c) => !c.pass && c.severity === "BLOCKER");
  const selfWarns: { id: string; explain: string }[] = [
    ...selfReport.checks.filter((c) => !c.pass && c.severity === "WARN").map((c) => ({ id: c.id, explain: c.explain })),
    ...selfReport.flags.map((f) => ({ id: f.id, explain: f.explain })),
  ];

  const eROIColor = eROI == null ? "var(--text-muted)" : eROI >= 2 ? "#10b981" : eROI >= 1 ? "#3b82f6" : "#ef4444";
  const margColor = marginalEROI == null ? "var(--text-muted)" : marginalEROI >= 1 ? "#10b981" : marginalEROI >= 0 ? "#3b82f6" : "#ef4444";
  const eNPVColor = eNPVM >= 0 ? "var(--accent)" : "var(--danger, #ef4444)";

  return (
    <div style={{
      border: `1.5px solid ${color}50`,
      borderRadius: 12,
      background: "var(--surface)",
      flex: "1 1 220px",
      minWidth: 0,
      display: "flex",
      flexDirection: "column",
    }}>
      {/* Option label header */}
      <div style={{
        background: `${color}18`,
        borderBottom: `1px solid ${color}30`,
        padding: "10px 14px",
        display: "flex", alignItems: "center", gap: 8,
      }}>
        <span style={{
          width: 24, height: 24, borderRadius: "50%",
          background: color, color: "#fff",
          fontSize: 11, fontWeight: 800, flexShrink: 0,
          display: "flex", alignItems: "center", justifyContent: "center",
          fontFamily: "var(--font-display)",
        }}>
          {label}
        </span>
        <span style={{ fontSize: 13, fontWeight: 700, color: "var(--text)", fontFamily: "var(--font-display)", flex: 1, minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
          {result.option.name || `Option ${label}`}
        </span>
        {isBaseline && (
          <span style={{ fontSize: 10, fontWeight: 600, padding: "2px 7px", borderRadius: 20, background: `${color}25`, color }}>
            BASELINE
          </span>
        )}
        {isAutoGenerated && (
          <span style={{ fontSize: 10, fontWeight: 600, padding: "2px 7px", borderRadius: 20, background: `${color}25`, color }}>
            SUGGESTED
          </span>
        )}
        {isRecommended && (
          <span title="Highest eNPV in the engine comparison" style={{ fontSize: 10, fontWeight: 700, padding: "2px 7px", borderRadius: 20, background: "rgba(16,185,129,0.18)", color: "#10b981", whiteSpace: "nowrap" }}>
            ★ BEST eNPV
          </span>
        )}
      </div>

      {/* Why this option exists (auto-generated Early-Signal Resolver only) */}
      {isAutoGenerated && (
        <div style={{ padding: "8px 14px", fontSize: 11, color: "var(--text-faint)", borderBottom: "1px solid var(--border)", lineHeight: 1.5 }}>
          Your evidence review found two very different possible outcomes for this drug — one where it works as hoped, one where it doesn't.
          This smaller, faster study is sized to reveal which one is true before you commit to the full next-stage trial.
        </div>
      )}

      {/* What changed — AI-generated summary of input differences */}
      {!isBaseline && result.option.changesSummary && (
        <div style={{
          padding: "8px 14px", fontSize: 11, color: "var(--text-muted)",
          borderBottom: "1px solid var(--border)", lineHeight: 1.5,
          background: `${color}06`,
        }}>
          <span style={{ fontWeight: 700, color, fontSize: 10, textTransform: "uppercase", letterSpacing: "0.05em" }}>What changed: </span>
          {result.option.changesSummary}
        </div>
      )}

      {/* Design summary — trial-design levers from the option, but the peak /
          cost / P(approval) numbers come from the ENGINE result (never the LLM's
          overrides), so this line can't contradict the tiles below. */}
      {!isBaseline && (
        <div style={{ padding: "6px 14px", fontSize: 11, color: "var(--text-faint)", borderBottom: "1px solid var(--border)", fontFamily: "var(--font-mono)" }}>
          {[
            result.option.designType?.replace("_", " ") ?? "",
            result.option.n ? `n=${result.option.n}` : "",
            result.option.regulatoryContext !== "standard" ? result.option.regulatoryContext?.replace("_", "+") : "",
            result.option.inclusionCriteria !== "standard" && result.option.inclusionCriteria ? result.option.inclusionCriteria : "",
            `peak $${Math.round(result.peakSalesM).toLocaleString()}M`,
            `cost $${Math.round(result.devCostM).toLocaleString()}M`,
            `P(appr) ${(result.ptrs * 100).toFixed(0)}%`,
          ].filter(Boolean).join(" · ")}
        </div>
      )}

      {/* Primary metrics */}
      <div style={{ padding: "14px 14px 6px" }}>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12, marginBottom: 12 }}>
          {/* eROI */}
          <div>
            <div style={{ fontSize: 10, color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 3 }}>eROI</div>
            <div style={{ fontSize: 26, fontWeight: 800, color: eROIColor, fontFamily: "var(--font-display)", lineHeight: 1 }}>
              {eROI != null ? fmtX(eROI) : "—"}
            </div>
            <div style={{ fontSize: 10, color: "var(--text-faint)", marginTop: 2 }}>eNPV / Dev Cost</div>
          </div>
          {/* Marginal eROI */}
          <div>
            <div style={{ fontSize: 10, color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 3 }}>
              {isBaseline ? "Marginal eROI" : "Marginal vs A"}
            </div>
            <div style={{ fontSize: 26, fontWeight: 800, fontFamily: "var(--font-display)", lineHeight: 1, color: isBaseline ? "var(--text-faint)" : margColor }}>
              {isBaseline ? "—" : marginalEROI != null ? fmtX(marginalEROI) : (deltaCostM === 0 ? "∞" : "—")}
            </div>
            <div style={{ fontSize: 10, color: "var(--text-faint)", marginTop: 2 }}>
              {isBaseline ? "baseline" : deltaCostM != null && deltaCostM < 0 ? "per $ saved" : "per $ spent"}
            </div>
          </div>
        </div>

        {/* eNPV */}
        <div style={{ marginBottom: 12 }}>
          <div style={{ fontSize: 10, color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 3 }}>eNPV</div>
          <div style={{ fontSize: 22, fontWeight: 700, color: eNPVColor, fontFamily: "var(--font-mono)" }}>
            {fmtM(eNPVM)}
          </div>
          <div style={{ fontSize: 10, color: "var(--text-faint)", marginTop: 2 }}>
            range {fmtM(eNPVLowM)} – {fmtM(eNPVHighM)}
          </div>
        </div>

        {/* Secondary metrics */}
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginBottom: 12 }}>
          <div>
            <div style={{ fontSize: 10, color: "var(--text-muted)", marginBottom: 2 }}>P(approval)</div>
            <div style={{ fontSize: 14, fontWeight: 700, color: "var(--text)", fontFamily: "var(--font-mono)" }}>
              {fmtPct(ptrs)}
            </div>
            <div style={{ fontSize: 10, color: "var(--text-faint)" }}>
              {fmtPct(ptrsCI.lower, 0)}–{fmtPct(ptrsCI.upper, 0)}
            </div>
          </div>
          <div>
            <div style={{ fontSize: 10, color: "var(--text-muted)", marginBottom: 2 }}>Peak Sales</div>
            <div style={{ fontSize: 14, fontWeight: 700, color: "var(--text)", fontFamily: "var(--font-mono)" }}>
              {fmtM(peakSalesM)}
            </div>
          </div>
          <div>
            <div style={{ fontSize: 10, color: "var(--text-muted)", marginBottom: 2 }}>Dev Cost</div>
            <div style={{ fontSize: 14, fontWeight: 700, color: "var(--text)", fontFamily: "var(--font-mono)" }}>
              {fmtM(devCostM)}
            </div>
          </div>
          <div>
            <div style={{ fontSize: 10, color: "var(--text-muted)", marginBottom: 2 }}>Revenue PV</div>
            <div style={{ fontSize: 14, fontWeight: 700, color: "var(--text)", fontFamily: "var(--font-mono)" }}>
              {fmtM(result.revenuePVM)}
            </div>
          </div>
          {durationMonths != null && (
            <div>
              <div style={{ fontSize: 10, color: "var(--text-muted)", marginBottom: 2 }}>Est. Trial Duration</div>
              <div style={{ fontSize: 14, fontWeight: 700, color: "var(--text)", fontFamily: "var(--font-mono)" }}>
                {durationMonths}mo
              </div>
            </div>
          )}
        </div>

        {/* vs Option A delta row */}
        {!isBaseline && (deltaENPVM != null || deltaCostM != null) && (
          <div style={{
            background: "var(--surface-2)", borderRadius: 8, padding: "8px 10px",
            fontSize: 12, fontFamily: "var(--font-mono)", marginBottom: 10,
          }}>
            <div style={{ color: "var(--text-muted)", marginBottom: 4 }}>vs Option A</div>
            <div style={{ display: "flex", gap: 12, flexWrap: "wrap" }}>
              {deltaENPVM != null && (
                <span style={{ color: deltaENPVM >= 0 ? "#10b981" : "#ef4444", fontWeight: 600 }}>
                  {deltaENPVM >= 0 ? "+" : ""}{fmtM(deltaENPVM)} eNPV
                </span>
              )}
              {deltaCostM != null && (
                <span style={{ color: deltaCostM > 0 ? "#ef4444" : "#10b981", fontWeight: 600 }}>
                  {deltaCostM >= 0 ? "+" : ""}{fmtM(deltaCostM)} cost
                </span>
              )}
            </div>
            {marginalEROI != null && (
              <div style={{ fontSize: 11, color: "var(--text-faint)", marginTop: 4 }}>
                Marginal dollar: {fmtX(marginalEROI)} return {deltaCostM != null && deltaCostM < 0 ? "(per $ saved)" : "(per $ spent)"}
              </div>
            )}
          </div>
        )}

        {/* VOI result */}
        {voiENPVM != null && (
          <div style={{
            background: "rgba(59,130,246,0.08)", border: "1px solid rgba(59,130,246,0.2)",
            borderRadius: 8, padding: "8px 10px", marginBottom: 10, fontSize: 12,
          }}>
            <div style={{ color: "var(--text-muted)", marginBottom: 4, fontSize: 10, textTransform: "uppercase", letterSpacing: "0.07em" }}>VOI Path</div>
            <div style={{ fontFamily: "var(--font-mono)", fontWeight: 600, color: voiENPVM >= 0 ? "#10b981" : "#ef4444" }}>
              {fmtM(voiENPVM)} expected value
            </div>
            {result.voiVsDirectM != null && (
              <div style={{ fontSize: 11, color: "var(--text-faint)", marginTop: 2 }}>
                {result.voiVsDirectM >= 0 ? "+" : ""}{fmtM(result.voiVsDirectM)} vs going direct (Option A)
              </div>
            )}
          </div>
        )}

        {/* Per-option development path — the engine's already-computed plan for THIS option, rendered
            with the same trial-box spine as the base dev-path (render-only; additive surfacing). */}
        {result.devPlan && (
          <div>
            <div style={{ fontSize: 10, color: "var(--text-muted)", marginBottom: 4, textTransform: "uppercase", letterSpacing: "0.07em" }}>Development path</div>
            <DevPathSpine devPlan={result.devPlan} />
          </div>
        )}

        {/* Key drivers */}
        {keyDrivers.length > 0 && (
          <div>
            <div style={{ fontSize: 10, color: "var(--text-muted)", marginBottom: 4, textTransform: "uppercase", letterSpacing: "0.07em" }}>Key Drivers</div>
            {keyDrivers.map((d, i) => (
              <div key={i} style={{ fontSize: 11, color: "var(--text-faint)", padding: "2px 0", display: "flex", gap: 6 }}>
                <span style={{ color: color }}>▸</span> {d}
              </div>
            ))}
          </div>
        )}

        {/* Self-check (read-only plausibility layer; observes & flags, never adjusts) */}
        <div>
          <div style={{ fontSize: 10, color: "var(--text-muted)", marginBottom: 4, textTransform: "uppercase", letterSpacing: "0.07em" }}>Checks</div>
          {selfBlockers.length === 0 && selfWarns.length === 0 && (
            <div style={{ fontSize: 11, color: "var(--text-faint)" }}>✓ self-check: no issues</div>
          )}
          {selfBlockers.map((c) => (
            <div key={c.id} style={{ fontSize: 11, color: "#ef4444", fontWeight: 700, padding: "2px 0" }}>⛔ {c.explain}</div>
          ))}
          {selfWarns.map((w) => (
            <div key={w.id} style={{ fontSize: 11, color: "#f59e0b", padding: "2px 0" }}>⚠ {w.explain}</div>
          ))}
        </div>

        {/* Layer 2 — "describe a design" (text → /api/design-interpreter → validated spec → existing
            recompute). The browser NEVER builds a spec or computes a number: it POSTs raw text and
            renders the endpoint's {spec, flags, assumptions} + the engine's recomputed result. */}
        {!isBaseline && onApplyDesign && (
          <div>
            <div style={{ fontSize: 10, color: "var(--text-muted)", marginBottom: 4, textTransform: "uppercase", letterSpacing: "0.07em" }}>Describe a design</div>
            <textarea
              value={designText}
              onChange={(e) => setDesignText(e.target.value)}
              placeholder="e.g. add a futility interim at 50% on Phase 3, one-sided alpha 0.025"
              rows={2}
              style={{ width: "100%", fontSize: 11, padding: "6px 8px", borderRadius: 8, border: "1px solid var(--border)", background: "var(--surface)", color: "var(--text)", resize: "vertical", fontFamily: "inherit" }}
            />
            <button
              className="btn"
              disabled={designPending}
              onClick={async () => {
                setDesignPending(true);
                setDesignError(null);
                const res = await onApplyDesign(result.option.id, designText.trim());
                setDesignPending(false);
                if (!res.ok) setDesignError(res.error ?? "design interpretation failed");
              }}
              style={{ fontSize: 11, padding: "4px 10px", marginTop: 4 }}
            >
              {designPending ? "Interpreting…" : designText.trim() ? "Apply design" : "Clear design"}
            </button>
            {designError && (
              <div style={{ fontSize: 11, color: "#ef4444", marginTop: 4 }}>⚠ {designError} — design not applied (running the current plan)</div>
            )}
            {result.designProvenance && (
              <div style={{ marginTop: 6, fontSize: 11, color: "var(--text-faint)" }}>
                {/* Assumptions — what the interpreter filled/defaulted, shown so the user SEES it (esp. a
                    default stageTarget or an alpha override) and can change it. */}
                {result.designProvenance.assumptions.map((a, i) => (
                  <div key={`da${i}`} style={{ padding: "1px 0" }}>
                    <span style={{ color: a.source === "default" ? "#f59e0b" : "var(--text-muted)" }}>{a.source === "default" ? "assumed" : a.source}:</span> {a.field} = {String(a.value)}
                  </div>
                ))}
                {/* Flags — interpreter validation + stage-target resolution. An unsupported design shows
                    BOTH the "not computable yet" (fallback) and the "computed with Y" (info) lines. */}
                {result.designProvenance.flags.map((f, i) => (
                  <div key={`df${i}`} style={{ padding: "1px 0", color: f.severity === "reject" ? "#ef4444" : f.severity === "fallback" ? "#f59e0b" : "var(--text-faint)" }}>
                    {f.severity === "reject" ? "✗" : f.severity === "fallback" ? "⚠" : "·"} {f.message}
                  </div>
                ))}
                {/* computeStageRR flags on the targeted stage (PP/CP-deferred, binding-non-converge). */}
                {result.designProvenance.stageFlags?.map((sf, i) => (
                  <div key={`ds${i}`} style={{ padding: "1px 0", color: "#f59e0b" }}>⚠ {sf}</div>
                ))}
                {/* E[N] surfaced — an OUTPUT (not priced into cost this pass). */}
                {result.designProvenance.sequentialDesign && (
                  <div style={{ padding: "1px 0" }}>
                    E[N] ≈ {Math.round(result.designProvenance.sequentialDesign.expectedN)} (expected sample size; surfaced, not priced into cost)
                    {result.designProvenance.sequentialDesign.achievedTypeI != null ? ` · binding type-I ${(result.designProvenance.sequentialDesign.achievedTypeI * 100).toFixed(2)}%` : ""}
                  </div>
                )}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

// ─── Charts ───────────────────────────────────────────────────────────────────

function ComparisonCharts({ results }: { results: OptionResult[] }) {
  const labels = results.map((r, i) => r.option.name || `Option ${OPTION_LABELS[i]}`);

  const eROIData = results.map((r, i) => ({
    name: OPTION_LABELS[i] ?? String(i + 1),
    label: labels[i],
    eROI: r.eROI ?? 0,
    color: OPTION_COLORS[i] ?? "#6b7280",
  }));

  const eNPVData = results.map((r, i) => ({
    name: OPTION_LABELS[i] ?? String(i + 1),
    label: labels[i],
    eNPV: r.eNPVM,
    color: OPTION_COLORS[i] ?? "#6b7280",
  }));

  // Scatter: eNPV (y) vs Dev Cost (x) — efficiency frontier
  const scatterData = results.map((r, i) => ({
    devCost: r.devCostM,
    eNPV: r.eNPVM,
    name: OPTION_LABELS[i] ?? String(i + 1),
    label: labels[i],
    color: OPTION_COLORS[i] ?? "#6b7280",
  }));

  const tooltipStyle = {
    background: "var(--bg-card-solid)",
    border: "1px solid var(--border)",
    borderRadius: 8, fontSize: 12, color: "var(--text)",
  };

  return (
    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: 20 }}>
      {/* eROI bar chart */}
      <div>
        <div style={{ fontSize: 11, fontWeight: 600, color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 10 }}>
          eROI by Option
        </div>
        <ResponsiveContainer width="100%" height={160}>
          <BarChart data={eROIData} margin={{ top: 5, right: 10, bottom: 5, left: 0 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
            <XAxis dataKey="name" tick={{ fontSize: 11, fill: "var(--text-muted)" }} />
            <YAxis tick={{ fontSize: 10, fill: "var(--text-muted)" }} tickFormatter={(v) => `${v.toFixed(1)}x`} />
            <Tooltip
              contentStyle={tooltipStyle}
              formatter={(v: number, _: any, p: any) => [`${v.toFixed(2)}x`, p.payload.label]}
            />
            <Bar dataKey="eROI" radius={[4, 4, 0, 0]}>
              {eROIData.map((entry, i) => <Cell key={i} fill={entry.color} />)}
            </Bar>
          </BarChart>
        </ResponsiveContainer>
      </div>

      {/* eNPV bar chart */}
      <div>
        <div style={{ fontSize: 11, fontWeight: 600, color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 10 }}>
          eNPV by Option ($M)
        </div>
        <ResponsiveContainer width="100%" height={160}>
          <BarChart data={eNPVData} margin={{ top: 5, right: 10, bottom: 5, left: 0 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
            <XAxis dataKey="name" tick={{ fontSize: 11, fill: "var(--text-muted)" }} />
            <YAxis tick={{ fontSize: 10, fill: "var(--text-muted)" }} tickFormatter={(v) => `$${v.toFixed(0)}M`} />
            <Tooltip
              contentStyle={tooltipStyle}
              formatter={(v: number, _: any, p: any) => [`$${v.toFixed(0)}M`, p.payload.label]}
            />
            <Bar dataKey="eNPV" radius={[4, 4, 0, 0]}>
              {eNPVData.map((entry, i) => <Cell key={i} fill={entry.color} />)}
            </Bar>
          </BarChart>
        </ResponsiveContainer>
      </div>

      {/* Scatter: eNPV vs Dev Cost (efficiency frontier) */}
      <div>
        <div style={{ fontSize: 11, fontWeight: 600, color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 10 }}>
          eNPV vs Dev Cost — Efficiency Frontier
        </div>
        <div style={{ fontSize: 10, color: "var(--text-faint)", marginBottom: 8 }}>
          Up-right = best. Options dominated (lower eNPV, higher cost) are unfavorable.
        </div>
        <ResponsiveContainer width="100%" height={140}>
          <ScatterChart margin={{ top: 5, right: 20, bottom: 5, left: 0 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
            <XAxis type="number" dataKey="devCost" name="Dev Cost" tick={{ fontSize: 10, fill: "var(--text-muted)" }} tickFormatter={(v) => `$${v.toFixed(0)}M`} label={{ value: "Dev Cost ($M)", position: "insideBottom", offset: -2, fontSize: 10, fill: "var(--text-faint)" }} />
            <YAxis type="number" dataKey="eNPV" name="eNPV" tick={{ fontSize: 10, fill: "var(--text-muted)" }} tickFormatter={(v) => `$${v.toFixed(0)}M`} />
            <ZAxis range={[60, 60]} />
            <Tooltip
              contentStyle={tooltipStyle}
              content={({ payload }) => {
                if (!payload?.length) return null;
                const d = payload[0]?.payload;
                return (
                  <div style={{ ...tooltipStyle, padding: "8px 12px" }}>
                    <div style={{ fontWeight: 700 }}>{d.label}</div>
                    <div>eNPV: {fmtM(d.eNPV)}</div>
                    <div>Dev Cost: {fmtM(d.devCost)}</div>
                  </div>
                );
              }}
            />
            <Scatter data={scatterData} fill="#10b981">
              {scatterData.map((entry, i) => (
                <Cell key={i} fill={entry.color} />
              ))}
            </Scatter>
          </ScatterChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
}

// ─── Sensitivity Table ────────────────────────────────────────────────────────
// Shows how the ranking changes if PTRS assumptions shift ±10%.

function SensitivityTable({ results, base }: { results: OptionResult[]; base: BaseContext }) {
  const scenarios = [
    { label: "Bear (P(approval) −10%)", ptrsShift: -0.10 },
    { label: "Base",                    ptrsShift:  0    },
    { label: "Bull (P(approval) +10%)", ptrsShift: +0.10 },
  ];

  const tableResults = scenarios.map(({ label, ptrsShift }) =>
    results.map((r) => {
      const adjPtrs = Math.max(0.01, Math.min(0.99, r.ptrs + ptrsShift));
      const adjENPV = round1(adjPtrs * r.revenuePVM - r.devCostM);
      const adjROI  = r.devCostM > 0 ? round2(adjENPV / r.devCostM) : null;
      return { adjPtrs, adjENPV, adjROI };
    })
  );

  return (
    <div>
      <div style={{ fontSize: 11, fontWeight: 600, color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 12 }}>
        Sensitivity — Does the ranking change if P(approval) shifts ±10%?
      </div>
      <div style={{ overflowX: "auto" }}>
        <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 12, fontFamily: "var(--font-mono)" }}>
          <thead>
            <tr style={{ borderBottom: "1px solid var(--border)" }}>
              <th style={{ padding: "6px 10px", textAlign: "left", fontSize: 10, color: "var(--text-faint)", fontWeight: 600, textTransform: "uppercase" }}>Scenario</th>
              {results.map((r, i) => (
                <th key={i} style={{ padding: "6px 10px", textAlign: "right", fontSize: 10, color: OPTION_COLORS[i], fontWeight: 700, textTransform: "uppercase" }}>
                  {OPTION_LABELS[i]} — {r.option.name || `Option ${OPTION_LABELS[i]}`}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {scenarios.map((sc, si) => (
              <tr key={si} style={{ borderBottom: "1px solid var(--border)", background: si === 1 ? "var(--surface-2)" : undefined }}>
                <td style={{ padding: "7px 10px", fontWeight: si === 1 ? 700 : 400, color: si === 1 ? "var(--text)" : "var(--text-muted)" }}>
                  {sc.label}
                </td>
                {tableResults[si].map((cell, ci) => (
                  <td key={ci} style={{ padding: "7px 10px", textAlign: "right" }}>
                    <span style={{ fontWeight: 600, color: cell.adjENPV >= 0 ? OPTION_COLORS[ci] : "#ef4444" }}>
                      {fmtM(cell.adjENPV)}
                    </span>
                    <span style={{ color: "var(--text-faint)", marginLeft: 8 }}>
                      {cell.adjROI != null ? `(${cell.adjROI.toFixed(1)}x)` : ""}
                    </span>
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

function round1(x: number) { return Math.round(x * 10) / 10; }
function round2(x: number) { return Math.round(x * 100) / 100; }

// ─── Quick-prompt chip suggestions ───────────────────────────────────────────

const QUICK_PROMPTS = [
  "Compare biomarker-selected vs broad population",
  "What does out-licensing look like vs full development?",
  "Should we run a smaller pilot first or go straight to Phase 3?",
  "Show me aggressive vs conservative trial sizes",
  "What's the value of seeking Breakthrough Therapy Designation?",
];

// ─── Main Component ───────────────────────────────────────────────────────────

export default function DecisionAnalysis({ valuation, out, ptrsResult, layer2Result, effectPrior, devPlan, persisted, onPersistedChange }: Props) {
  const [open, setOpen] = useState(persisted?.open ?? false);
  const [options, setOptions] = useState<OptionInputs[]>(persisted?.options ?? []);
  const [aiSummary, setAiSummary] = useState<string | null>(persisted?.aiSummary ?? null);
  const [chatInput, setChatInput] = useState("");
  const [chatLoading, setChatLoading] = useState(false);
  const [chatError, setChatError] = useState<string | null>(null);
  const [chatHistory, setChatHistory] = useState<{ role: "user" | "assistant"; content: string }[]>(persisted?.chatHistory ?? []);
  const [aiInsight, setAiInsight] = useState<string | null>(persisted?.aiInsight ?? null);
  const [insightLoading, setInsightLoading] = useState(false);
  const textareaRef = React.useRef<HTMLTextAreaElement>(null);
  const insightFiredForRef = useRef<string>("");

  // Auto-restore on reload: the parent's `persisted` prop is null on first app mount and only arrives once
  // the last-active snapshot rehydrates (a render AFTER this component already mounted with empty state), so
  // the initial useState values above miss it. Seed ONCE, and ONLY for a genuine external restore —
  // reportedRef means that once WE'VE pushed state up, any later `persisted` is just our own echo (never a
  // restore), so we don't re-seed and can't clobber a live edit with a stale echo.
  const seededRef = useRef(false);
  const reportedRef = useRef(false);
  useEffect(() => {
    if (seededRef.current || reportedRef.current || !persisted) return;
    seededRef.current = true;
    setOpen(persisted.open ?? false);
    setOptions(persisted.options ?? []);
    setAiSummary(persisted.aiSummary ?? null);
    setAiInsight(persisted.aiInsight ?? null);
    setChatHistory(persisted.chatHistory ?? []);
  }, [persisted]);

  // Report generated state up so the parent can persist it. Skip the initial EMPTY state so we never
  // overwrite an incoming restore with blanks before the seed lands (and don't persist nothing).
  useEffect(() => {
    if (!options.length && !aiSummary && !aiInsight && !chatHistory.length) return;
    reportedRef.current = true;
    onPersistedChange?.({ open, options, aiSummary, aiInsight, chatHistory });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, options, aiSummary, aiInsight, chatHistory]);

  // Build base context from current valuation + PTRS results
  const base = useMemo(
    () => buildBaseContext(valuation, out, ptrsResult, layer2Result, effectPrior, devPlan),
    [valuation, out, ptrsResult, layer2Result, effectPrior, devPlan]
  );

  // Compute results from current option definitions, plus the auto-generated
  // Early-Signal Resolver option (if the effect prior is bimodal).
  const results = useMemo(() => {
    if (!base || options.length === 0) return [];
    const computed = computeAllOptions(base, options);
    const resolverOption = generateBimodalVoiOption(base);
    if (resolverOption) {
      const optionA = computed.find((r) => r.option.isBaseline) ?? computed[0];
      computed.push(computeOption(base, resolverOption, optionA));
    }
    return computed;
  }, [base, options]);

  // Layer 2 — POST free-form design text to the interpreter and set ONLY the validated spec it returns
  // on the option; the EXISTING recompute (computeOption) then threads designSpec → full valuation. The
  // client builds no spec and computes no number. Empty text → clear the spec (existing path). On
  // failure → set nothing (never a fabricated spec) and surface the error.
  async function applyDesign(optionId: string, text: string): Promise<{ ok: boolean; error?: string }> {
    if (!text) {
      setOptions((prev) => prev.map((o) => (o.id === optionId ? { ...o, designSpec: undefined, designFlags: undefined, designAssumptions: undefined } : o)));
      return { ok: true };
    }
    try {
      const res = await fetch("/api/design-interpreter", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ request: text }),
      });
      if (!res.ok) {
        const e = (await res.json().catch(() => ({}))) as { error?: string };
        return { ok: false, error: e?.error ?? `HTTP ${res.status}` };
      }
      const data = (await res.json()) as { spec: OptionInputs["designSpec"]; flags: OptionInputs["designFlags"]; assumptions: OptionInputs["designAssumptions"] };
      // Use ONLY what the endpoint returned — the validated spec + its flags/assumptions.
      setOptions((prev) => prev.map((o) => (o.id === optionId ? { ...o, designSpec: data.spec, designFlags: data.flags, designAssumptions: data.assumptions } : o)));
      return { ok: true };
    } catch (e: any) {
      return { ok: false, error: e?.message ?? "network error" };
    }
  }

  // Auto-fetch strategic insight once results are ready
  useEffect(() => {
    if (results.length < 2 || insightLoading) return;
    // Build a fingerprint so we don't re-fetch for the same results
    const fingerprint = results.map((r) => `${r.option.id}:${r.eNPVM}`).join("|");
    if (fingerprint === insightFiredForRef.current) return;
    insightFiredForRef.current = fingerprint;

    setInsightLoading(true);
    setAiInsight(null);
    fetch("/api/decision-analysis", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        drug: valuation.asset || valuation.name,
        phase: valuation.phase,
        options: results.map((r) => ({
          name: r.option.name || "unnamed",
          eNPVM: r.eNPVM,
          eROI: r.eROI,
          marginalEROI: r.marginalEROI,
          ptrs: r.ptrs,
          peakSalesM: r.peakSalesM,
          devCostM: r.devCostM,
          keyDrivers: r.keyDrivers,
          isVOI: r.option.isVOI,
          voiENPVM: r.voiENPVM,
        })),
      }),
    })
      .then((res) => (res.ok ? res.json() : Promise.reject(res.status)))
      .then((data) => setAiInsight(data.insight ?? null))
      .catch(() => setAiInsight(null))
      .finally(() => setInsightLoading(false));
  }, [results, valuation.asset, valuation.name, valuation.phase]); // eslint-disable-line react-hooks/exhaustive-deps

  // Build the strategy context payload (lightweight subset for the AI)
  function buildStrategyContext() {
    return {
      asset:       valuation.asset ?? valuation.name ?? "Unknown drug",
      phase:       valuation.phase ?? base?.phase ?? "Unknown phase",
      mechanism:   valuation.mechanism ?? "Unknown",
      indication:  valuation.indication ?? "Unknown",
      pApproval:   devPlan?.pApproval ?? base?.ptrs,
      peakSalesM:  base?.peakSalesM,
      eNPVM:       devPlan ? round1(devPlan.eNPVM) : null,
      devCostM:    base?.devCostM,
      effectShape: effectPrior?.shape,
      currentDesign: base ? {
        n:                 base.baseTrialDesign.n,
        endpointType:      base.baseTrialDesign.endpointType,
        designType:        base.baseTrialDesign.designType,
        populationType:    base.baseTrialDesign.populationType,
        regulatoryContext: base.baseTrialDesign.regulatoryContext,
        placeboResponse:   base.baseTrialDesign.placeboResponse,
      } : undefined,
      stages: devPlan?.stages?.map((s) => ({
        name:             s.name,
        phase:            s.phase,
        n:                s.n,
        cpp:              s.cpp,
        endpointType:     s.trialDesign.endpointType,
        designType:       s.trialDesign.designType,
        populationType:   s.trialDesign.populationType,
        trialSuccessProb: s.trialSuccessProb,
        durationMonths:   s.durationMonths,
      })),
    };
  }

  async function askAdvisor(message: string) {
    if (!message.trim() || chatLoading) return;
    setChatLoading(true);
    setChatError(null);

    const newHistory = [...chatHistory, { role: "user" as const, content: message }];
    setChatHistory(newHistory);
    setChatInput("");

    try {
      const res = await fetch("/api/decision-options", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          message,
          context: buildStrategyContext(),
          history: chatHistory, // send previous turns for follow-up refinement
        }),
      });

      const data = await res.json();

      if (!res.ok) {
        setChatError(data.error ?? `Request failed (${res.status})`);
        setChatHistory((prev) => prev.slice(0, -1)); // remove the user message on error
        return;
      }

      // If parsing failed entirely (no options), show clean error only
      if (data.parseError && (!Array.isArray(data.options) || data.options.length === 0)) {
        setChatError(data.parseError);
        setChatHistory((prev) => prev.slice(0, -1));
        return;
      }

      // Update options — always include baseline as Option A
      if (Array.isArray(data.options) && data.options.length > 0) {
        const hasBaseline = data.options.some((o: any) => o.isBaseline);
        const finalOptions: OptionInputs[] = hasBaseline
          ? data.options
          : [{ id: "opt-a", name: "Current Plan", isBaseline: true }, ...data.options];
        setOptions(finalOptions);
      }

      // Store the sanitized summary (never raw model text) + add to history
      if (data.summary) {
        setAiSummary(data.summary);
        setChatHistory((prev) => [
          ...prev,
          { role: "assistant" as const, content: data.summary },
        ]);
      }
    } catch (e) {
      setChatError("Network error — check your connection and try again.");
      setChatHistory((prev) => prev.slice(0, -1));
    } finally {
      setChatLoading(false);
    }
  }

  function handleKeyDown(e: React.KeyboardEvent<HTMLTextAreaElement>) {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      askAdvisor(chatInput);
    }
  }

  // Don't render if no drug has been entered
  if (!valuation.asset && !(valuation as any).name) return null;

  return (
    <div>
      {/* Entry point button */}
      {!open && (
        <button
          className="btn btn-outline"
          onClick={() => setOpen(true)}
          style={{ width: "100%", justifyContent: "center", fontSize: 14, padding: "12px 0", fontWeight: 700 }}
        >
          Strategy Advisor ↗
        </button>
      )}

      {open && (
        <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>

          {/* Panel header */}
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
            <div>
              <div style={{ fontSize: 18, fontWeight: 800, color: "var(--text)", fontFamily: "var(--font-display)" }}>
                Strategy Advisor
              </div>
              <div style={{ fontSize: 12, color: "var(--text-muted)", marginTop: 2 }}>
                Describe your strategic question or alternatives — the AI structures the options and runs the full valuation for each.
              </div>
            </div>
            <button className="btn btn-ghost" onClick={() => setOpen(false)} style={{ fontSize: 12, flexShrink: 0 }}>
              Close ×
            </button>
          </div>

          {/* No-data warning */}
          {!base && (
            <div style={{
              background: "rgba(251,191,36,0.1)", border: "1px solid rgba(251,191,36,0.3)",
              borderRadius: 10, padding: "16px 20px", fontSize: 13, color: "#92400e",
            }}>
              Run <strong>Auto-Valuate</strong> first to populate the drug context. The Strategy Advisor needs peak sales, dev cost, and approval probability data to compare options.
            </div>
          )}

          {/* Chat input area */}
          <div style={{
            background: "var(--surface)", border: "1px solid var(--border)",
            borderRadius: 14, overflow: "hidden",
          }}>
            {/* Quick-prompt chips */}
            {chatHistory.length === 0 && (
              <div style={{ padding: "14px 16px 0", display: "flex", flexWrap: "wrap", gap: 8 }}>
                <div style={{ fontSize: 11, color: "var(--text-faint)", width: "100%", marginBottom: 4 }}>
                  Try asking…
                </div>
                {QUICK_PROMPTS.map((p) => (
                  <button
                    key={p}
                    onClick={() => askAdvisor(p)}
                    disabled={chatLoading}
                    style={{
                      fontSize: 12, padding: "5px 12px", borderRadius: 20,
                      border: "1px solid var(--border)", background: "var(--surface-2)",
                      color: "var(--text-muted)", cursor: "pointer",
                      transition: "border-color 0.15s",
                    }}
                    onMouseEnter={(e) => (e.currentTarget.style.borderColor = "var(--accent)")}
                    onMouseLeave={(e) => (e.currentTarget.style.borderColor = "var(--border)")}
                  >
                    {p}
                  </button>
                ))}
              </div>
            )}

            {/* Conversation transcript — keep the user's questions visible after
                the advisor answers (the input clears on send). */}
            {chatHistory.length > 0 && (() => {
              const questions = chatHistory.filter((m) => m.role === "user");
              return (
                <div style={{ padding: "10px 16px", borderBottom: "1px solid var(--border)" }}>
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: questions.length > 0 ? 8 : 0 }}>
                    <div style={{ fontSize: 11, color: "var(--text-faint)" }}>
                      {questions.length} question{questions.length !== 1 ? "s" : ""} asked
                      {options.length > 0 && ` · ${options.length} options generated`}
                    </div>
                    <button
                      onClick={() => {
                        setChatHistory([]);
                        setOptions([]);
                        setAiSummary(null);
                        setChatError(null);
                      }}
                      style={{ fontSize: 11, color: "var(--text-faint)", background: "none", border: "none", cursor: "pointer" }}
                    >
                      Clear ×
                    </button>
                  </div>
                  <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                    {questions.map((m, i) => (
                      <div key={i} style={{ fontSize: 12.5, color: "var(--text)", background: "var(--surface-2)", borderRadius: 8, padding: "8px 12px", lineHeight: 1.5 }}>
                        <span style={{ color: "var(--text-faint)", fontWeight: 700, marginRight: 6, whiteSpace: "nowrap" }}>You asked:</span>
                        {m.content}
                      </div>
                    ))}
                  </div>
                </div>
              );
            })()}

            {/* Text input */}
            <div style={{ display: "flex", gap: 0, alignItems: "flex-end" }}>
              <textarea
                ref={textareaRef}
                value={chatInput}
                onChange={(e) => setChatInput(e.target.value)}
                onKeyDown={handleKeyDown}
                disabled={chatLoading}
                placeholder={chatHistory.length === 0
                  ? "E.g.: Compare going all-in on the current trial vs. biomarker selection first. Also show out-licensing."
                  : "Refine the options or ask a follow-up…"}
                rows={3}
                style={{
                  flex: 1, resize: "none", border: "none", outline: "none",
                  background: "transparent", padding: "14px 16px",
                  fontSize: 13, color: "var(--text)", lineHeight: 1.6,
                  fontFamily: "inherit",
                }}
              />
              <div style={{ padding: "0 12px 12px 0", flexShrink: 0 }}>
                <button
                  onClick={() => askAdvisor(chatInput)}
                  disabled={chatLoading || !chatInput.trim()}
                  style={{
                    background: chatLoading || !chatInput.trim() ? "var(--surface-2)" : "var(--accent)",
                    color: chatLoading || !chatInput.trim() ? "var(--text-faint)" : "#fff",
                    border: "none", borderRadius: 10, padding: "9px 20px",
                    fontSize: 13, fontWeight: 700, cursor: chatLoading || !chatInput.trim() ? "default" : "pointer",
                    transition: "background 0.15s",
                  }}
                >
                  {chatLoading ? "⏳" : "Analyze →"}
                </button>
              </div>
            </div>

            {/* Error */}
            {chatError && (
              <div style={{
                padding: "8px 16px 12px", fontSize: 12, color: "#ef4444",
                borderTop: "1px solid rgba(239,68,68,0.2)",
              }}>
                {chatError}
              </div>
            )}
          </div>

          {/* AI explanation */}
          {aiSummary && (
            <div style={{
              background: "linear-gradient(135deg, rgba(16,185,129,0.05), rgba(59,130,246,0.05))",
              border: "1px solid rgba(16,185,129,0.2)",
              borderRadius: 12, padding: "16px 18px",
            }}>
              <div style={{ fontSize: 10, color: "var(--accent)", textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 8, fontWeight: 700 }}>
                Strategy Advisor
              </div>
              <div style={{ fontSize: 13, color: "var(--text)", lineHeight: 1.75, whiteSpace: "pre-wrap" }}>
                {aiSummary}
              </div>
            </div>
          )}

          {/* Results */}
          {results.length > 0 && (
            <>
              <div>
                <div style={{ fontSize: 13, fontWeight: 700, color: "var(--text)", marginBottom: 12, fontFamily: "var(--font-display)" }}>
                  Comparison — full valuation per option
                </div>
                <div style={{ display: "flex", gap: 14, flexWrap: "wrap" }}>
                  {(() => {
                    // Engine-computed recommendation = highest eNPV. Replaces the
                    // LLM's prose star, which was driven by its (now-overridden) guesses.
                    const bestId = results.reduce((best, r) => (r.eNPVM > best.eNPVM ? r : best), results[0])?.option.id;
                    return results.map((r, i) => (
                    <ResultCard
                      key={r.option.id}
                      result={r}
                      index={i}
                      isBaseline={!!r.option.isBaseline || i === 0}
                      isAutoGenerated={r.option.id === "voi-resolver"}
                      isRecommended={r.option.id === bestId}
                      onApplyDesign={applyDesign}
                    />
                  ));
                  })()}
                </div>
              </div>

              <div style={{ background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 12, padding: 20 }}>
                <ComparisonCharts results={results} />
              </div>

              <div style={{ background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 12, padding: 20 }}>
                <SensitivityTable results={results} base={base!} />
              </div>

              {/* AI strategic insight — auto-generated */}
              <div style={{
                background: "var(--surface)", border: "1px solid var(--border)",
                borderRadius: 12, padding: 20,
              }}>
                <div style={{ fontSize: 11, fontWeight: 700, color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 10 }}>
                  Strategic Insight
                </div>
                {insightLoading ? (
                  <div style={{ fontSize: 13, color: "var(--text-faint)" }}>Generating strategic insight…</div>
                ) : aiInsight ? (
                  <div style={{
                    background: "rgba(16,185,129,0.06)", border: "1px solid rgba(16,185,129,0.15)",
                    borderRadius: 8, padding: "12px 16px", fontSize: 13, color: "var(--text)", lineHeight: 1.7,
                  }}>
                    {aiInsight}
                  </div>
                ) : (
                  <div style={{ fontSize: 12, color: "var(--text-faint)" }}>
                    Insight unavailable — check API credits.
                  </div>
                )}
              </div>

              <div style={{ fontSize: 11, color: "var(--text-faint)", lineHeight: 1.6, fontFamily: "var(--font-mono)" }}>
                eNPV = P(approval) × Revenue PV − Dev Cost PV · eROI = eNPV / Dev Cost · Marginal eROI = ΔeNPV / |ΔDev Cost| vs Option A ·
                P(approval) recalculated per option via full multi-stage development plan · Dev cost = CPP × n per patient · Peak sales re-derived bottom-up per scenario: eligible patients × annual WAC × peak share % (not a multiple of the base peak)
              </div>
            </>
          )}
        </div>
      )}
    </div>
  );
}
